In [1]:
#joining DataFrames & Metrics together

In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [8]:
#in Numpy

arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1, arr1]) #concat rows

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.concatenate([arr1, arr1], axis=1) #concat columns

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [9]:
#in Pandas

In [10]:
ser1 = Series([0,1,2], index=['T', 'U', 'V'])
ser2 = Series([3,4], index=['X', 'Y'])

In [11]:
ser1

T    0
U    1
V    2
dtype: int64

In [12]:
ser2

X    3
Y    4
dtype: int64

In [14]:
pd.concat([ser1,ser2]) 

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [17]:
pd.concat([ser1, ser2], axis=1) #concat on columns -- creates DataFrame

C:\Users\parikshitas\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [18]:
#add markers/keys on result
pd.concat([ser1, ser2], keys=['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [22]:
#for dataframe
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])

dframe2 = DataFrame(np.random.randn(3,3), columns=['Y', 'Q', 'X'])

In [23]:
dframe1

X         Y         Z
0 -0.067224  1.033303  2.250536
1  0.313381  1.382553 -0.572554
2  0.268269 -1.659380 -0.284043
3 -0.524171  1.040649  1.130403

In [24]:
dframe2

Y         Q         X
0 -1.762006 -0.226617 -0.058165
1 -0.482407 -0.309574  1.638890
2 -0.644864 -1.301061 -1.117538

In [26]:
pd.concat([dframe1, dframe2])

C:\Users\parikshitas\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN -0.067224  1.033303  2.250536
1       NaN  0.313381  1.382553 -0.572554
2       NaN  0.268269 -1.659380 -0.284043
3       NaN -0.524171  1.040649  1.130403
0 -0.226617 -0.058165 -1.762006       NaN
1 -0.309574  1.638890 -0.482407       NaN
2 -1.301061 -1.117538 -0.644864       NaN

In [27]:
#ignoring the index, in above example 0 1 2 3 0 1 2 will become 0 1 2 3 4 5 6
pd.concat([dframe1, dframe2], ignore_index=True)

C:\Users\parikshitas\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


Q         X         Y         Z
0       NaN -0.067224  1.033303  2.250536
1       NaN  0.313381  1.382553 -0.572554
2       NaN  0.268269 -1.659380 -0.284043
3       NaN -0.524171  1.040649  1.130403
4 -0.226617 -0.058165 -1.762006       NaN
5 -0.309574  1.638890 -0.482407       NaN
6 -1.301061 -1.117538 -0.644864       NaN