In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]

In [3]:
my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2 = [11,22,33,44]

In [6]:
my_lists = [my_list1, my_list2]

In [7]:
print(my_lists)

[[1, 2, 3, 4], [11, 22, 33, 44]]


In [8]:
my_array2 = np.array(my_lists)

In [9]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [10]:
my_array2.shape

(2, 4)

my_array2.dtype

In [11]:
my_array2.dtype

dtype('int32')

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones([5,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [18]:
awd

NameError: name 'awd' is not defined

In [ ]:
pwd