In [11]:
import numpy as np

In [12]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [13]:
np.save('myarray', arr)

In [14]:
arr = np.arange(10)

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr1 = np.load('myarray.npy')

In [17]:
arr2 = arr
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.savez('ziparray.npz',x=arr1,y=arr2)

In [18]:
archive_array = np.load('ziparray.npz')

In [19]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [20]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.savetxt('mytextarray.txt',arr,delimiter=',')

In [25]:
arr = np.loadtxt('mytextarray.txt',delimiter=',')

In [26]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])