In [1]:
import numpy as np

In [4]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [7]:
A = np.random.randn(10)
A

array([ 0.49373285,  0.27063966, -0.05441448, -1.06315272,  0.3501306 ,
        1.72109579, -1.41322597,  1.03035443,  1.47041571,  0.75547539])

In [8]:
B = np.random.randn(10)
B

array([ 0.05350569,  0.4525372 , -0.85756721,  1.42497506, -1.09235013,
       -0.16545737, -0.23043542,  0.0701936 ,  1.6489084 , -0.86110333])

In [9]:
#Binary functions
np.add(A,B)

array([ 0.54723854,  0.72317686, -0.91198169,  0.36182234, -0.74221953,
        1.55563842, -1.6436614 ,  1.10054803,  3.11932411, -0.10562794])

In [10]:
np.maximum(A,B)

array([ 0.49373285,  0.4525372 , -0.05441448,  1.42497506,  0.3501306 ,
        1.72109579, -0.23043542,  1.03035443,  1.6489084 ,  0.75547539])

In [11]:
website = 'https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open_new_tab(website)

True