In [24]:
import numpy as np

In [25]:
my_list1 = [1,2,3,4]

In [26]:
my_array1 = np.array(my_list1)

In [27]:
my_array1

array([1, 2, 3, 4])

In [28]:
my_list2 = [11,22,33,44]

In [29]:
my_lists = [my_list1, my_list2]

In [30]:
print(my_lists)

[[1, 2, 3, 4], [11, 22, 33, 44]]


In [31]:
my_array2 = np.array(my_lists)

In [32]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [33]:
my_array2.shape

(2, 4)

my_array2.dtype

In [34]:
my_array2.dtype

dtype('int32')

In [35]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [38]:
np.ones([5,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [42]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [44]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [45]:
awd

NameError: name 'awd' is not defined

In [47]:
pwd

'C:\\Users\\parikshitas'